const WEB_DEV_KEYWORDS = {
  trusted: new Set([
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "Next.js",
    "Node.js",
    "Nextjs",
    "Nodejs",
    "GraphQL",
    "REST",
    "Webpack",
    "TypeScript",
    "Tailwind CSS",
    "MongoDB",
    "AWS",
    "SSR",
    "CSR",
  ]),
  notSure: new Set([
    [
      "Code",
      "Script",
      "Compile",
      "Debug",
      "Function",
      "Variable",
      "Framework",
      "Library",
      "Module",
      "Package",
      "CLI",
      "Open Source",
      "Middleware",
      "Callback",
      "Algorithm",

      "UI",
      "UX",
      "Design",
      "Layout",
      "Template",
      "Component",
      "Widget",
      "Style",
      "Animation",
      "Transition",
      "Wireframe",
      "Prototype",

      "Server",
      "Endpoint",
      "Request",
      "Response",
      "Cloud",
      "Database",
      "Schema",
      "Query",
      "Token",
      "Authentication",
      "Authorization",
      "Deployment",
      "Pipeline",
      "Middleware",

      "Git",
      "CI/CD",
      "Build",
      "Repo",
      "Branch",
      "Terminal",
      "Shell",
      "Environment",
      "Container",
      "Port",
      "Logging",

      "API",
      "SDK",
      "Plugin",
      "Extension",
      "Tool",
      "Config",
      "Performance",
      "Optimization",
      "Debugger",
      "Log",
      "Testing",
      "Cache",

      "AI",
      "Machine Learning",
      "Blockchain",
      "IoT",
      "Automation",
      "Microservices",
      "SaaS",
      "Edge",
      "VR",
      "AR",
    ],
  ]),
};

export const KEYWORDS_REGEX = {
  trusted: new RegExp(
    [...WEB_DEV_KEYWORDS.trusted]
      .map((keyword) => `\\b${keyword}\\b`)
      .join("|"),
    "i",
  ),
  notSure: new RegExp(
    [...WEB_DEV_KEYWORDS.notSure]
      .map((keyword) => `\\b${keyword}\\b`)
      .join("|"),
    "i",
  ),
};

export const BLACKLIST = {
  labels: ["porn", "sexual", "graphic-media", "nudity"],
};
